<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNXdxxpe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNXdxxpe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNXdxxpe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNXdxxpe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNXdxxpe\App_KernelDevDebugContainer([
    'container.build_hash' => 'NXdxxpe',
    'container.build_id' => 'eda3d91e',
    'container.build_time' => 1679066847,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNXdxxpe');
